In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# display settings
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [140]:
np.random.seed(42)
t1 = np.random.randint(1, 100, 1000)
t2 = np.random.randint(1, 300, 300)
t3 = np.random.randint(1, 1000, 200)

m1 = np.random.randint(1, 20, 1000)
m2 = np.random.randint(5, 20, 30)
m3 = np.random.randint(10, 20, 200)

# print(t1 / m1)
# print(t2 / m2)
# print(t3 / m3)
# t1, t2, t3, m1, m2, m3

In [128]:
pt1 = np.random.randint(1, 10, 50)
d1 = pt1 * 1.2 + np.random.randn(50)
pt1, d1, pt1 / d1

(array([4, 7, 2, 3, 1, 5, 1, 8, 1, 1, 2, 2, 6, 7, 5, 1, 1, 3, 2, 5, 6, 7,
        4, 7, 8, 1, 6, 8, 5, 4, 2, 6, 6, 1, 9, 6, 3, 4, 4, 3, 3, 3, 4, 7,
        4, 9, 1, 8, 7, 2]),
 array([ 5.28197914,  9.32645636,  1.56241861,  4.27718607,  3.07231912,
         6.39637394,  0.5743837 ,  9.07753852,  1.2130339 ,  1.57776959,
         2.4628246 ,  2.90159637,  7.05305461,  8.58062297,  6.96481058,
         0.13516885,  1.3087118 ,  3.70576365,  3.32066672,  5.77327754,
         7.85304831,  9.50268747,  2.95019706,  9.56863124,  8.6146182 ,
         0.10605959,  4.32054311,  8.79682233,  5.99514306,  4.41667669,
         1.93747314,  6.08750265,  8.0672295 ,  2.15841384, 11.21811852,
         5.31347195,  5.87334516,  4.94697465,  5.3396092 ,  2.10170436,
         3.58855655,  4.01335409,  4.65910145,  9.27216186,  6.10034515,
         9.45647624,  2.05012058,  9.99433995,  8.39530401,  0.82918802]),
 array([0.7572919 , 0.75055302, 1.28006668, 0.70139572, 0.32548702,
        0.78169289, 1.74099647, 0.88129618, 0.82437927, 0.63380611,
        0.8120757 , 0.68927575, 0.85069524, 0.81579158, 0.71789461,
        7.39815439, 0.76411017, 0.80954974, 0.60228869, 0.86605918,
        0.76403452, 0.73663372, 1.35584163, 0.73155709, 0.92865404,
        9.42866167, 1.3887143 , 0.9094193 , 0.83400846, 0.90565832,
        1.03227238, 0.98562586, 0.74374976, 0.46330318, 0.80227357,
        1.12920517, 0.51078217, 0.80857499, 0.74911849, 1.42741294,
        0.83599073, 0.74750444, 0.85853464, 0.75494799, 0.6557006 ,
        0.95172872, 0.48777619, 0.80045306, 0.83379947, 2.4119982 ]))

In [148]:
from sklearn.preprocessing import minmax_scale

processing_time_1 = []
processing_time_2 = []
due_time = []
stage1_machines = []
stage2_machines = []

for i in range(len(t1)):
    
    if (t1[i] / m1[i] > 15):
        continue
        
    
    pt1 = np.random.randint(1, 100, t1[i]) / 10
#     print(pt1)
    pt2 = (np.random.randint(0, 120, t1[i])) / 10 - 2
    
    # make nan probability larger
    pt2[pt2 < 0] = 0
#     print("pt2", pt2)
#     print(pt1 + pt2)
    
    # positive correlation between processing time and due time + error
    # try to lower the possibility of doomed-to-be tardy jobs
    d1 = (pt1 + pt2) * 1.2 + np.random.randn(t1[i]) * 5 + 2
    d1 = d1.round(decimals=1)
    
    # upper and lower bound
    d1[d1 < 1] = 1
    d1[d1 > 24] = 24
    
    
    if (sum(pt1 + pt2) > 1.5 * m1[i] * 24):
        continue
        
    if (sum(pt1 + pt2 > d1) > t1[i] * 0.2):
        continue
    
#     print("d1", d1)
#     print("job num:", t1[i])
#     print("less than:", sum(pt1 + pt2 > d1))
#     print("operation time:", m1[i] * 24)
#     print("due time:", sum(d1))
#     print("process time:", sum(pt1 + pt2))
    
#     plt.scatter(pt1 + pt2, d1)
#     plt.xlabel("total processing time")
#     plt.ylabel("due time");
#     plt.show()
    
    processing_time_1.append(pt1)
    processing_time_2.append(pt2)
    due_time.append(d1)
    
    # machine
    unable = np.random.randint(1, t1[i], int(t1[i] / 3))
    
    stage1_machine = ""
    for m in range(1, m1[i] + 1):
        stage1_machine += str(m) + ","
    stage1_machine.rstrip(",")
    
    stage2_machine = ""
    for m in range(1, m1[i] + 1):
        if m in unable:
            continue
        stage2_machine += str(m) + ","
    stage2_machine.rstrip(",")
    
    stage1_machines.append(stage1_machine)
    stage2_machines.append(stage2_machine)
    
#     print("stage 1 machine:", stage1_machine)
#     print("stage 2 machine:", stage2_machine)
    
print(len(due_time))

190

In [142]:
if os.getcwd() != '/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase':
    os.chdir('/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase')
if not os.path.exists('testcases'):
    os.makedirs('testcases')

os.chdir("testcases")
os.getcwd()

'/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/testcase/testcases'

In [157]:
for i in range(len(due_time)):
    df = pd.DataFrame(due_time[i], columns=["Due Time"])
    df["Stage-1 Processing Time"] = processing_time_1[i]
    df["Stage-2 Processing Time"] = processing_time_2[i]
    df["Stage-1 Machines"] = stage1_machines[i]
    df["Stage-2 Machines"] = stage2_machines[i]
    
    no_stage2 = (df["Stage-2 Processing Time"] == 0)
    df.loc[no_stage2, "Stage-2 Machines"] = np.nan
    print(df[no_stage2])   
    
    df.to_csv("instance " + str(i + 1) + ".csv")

    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
3     8.9000                   2.5000                   0.0000
6     1.0000                   4.8000                   0.0000
12   14.5000                   3.7000                   0.0000

         Stage-1 Machines Stage-2 Machines
3   1,2,3,4,5,6,7,8,9,10,              NaN
6   1,2,3,4,5,6,7,8,9,10,              NaN
12  1,2,3,4,5,6,7,8,9,10,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
8    15.3000                   8.8000                   0.0000
10   15.3000                   9.9000                   0.0000
28    4.4000                   5.3000                   0.0000
50   17.3000                   5.2000                   0.0000
57    1.4000                   1.1000                   0.0000

                              Stage-1 Machines Stage-2 Machines
8   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
10  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
28  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
50  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
57  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
5     7.6000                   5.1000                   0.0000
20    1.0000                   0.8000                   0.0000

                     Stage-1 Machines Stage-2 Machines
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
20  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
2     1.0000                   0.2000                   0.0000
6     4.1000                   2.8000                   0.0000
9    13.3000                   8.8000                   0.0000
14   14.2000                   8.4000                   0.0000
26   13.8000                   8.3000                   0.0000
28    4.6000                   4.1000                   0.0000

                  Stage-1 Machines Stage-2 Machines
2   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
6   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
9   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
26  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
28  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
10    8.1000                   5.5000                   0.0000
18   12.1000                   7.7000                   0.0000
29    3.0000                   0.3000                   0.0000
34    1.0000                   3.3000                   0.0000
36    1.0000                   0.3000                   0.0000
40    1.0000                   2.1000                   0.0000

                  Stage-1 Machines Stage-2 Machines
10  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
18  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
29  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
34  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
36  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
40  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6    8.0000                   5.2000                   0.0000

                             Stage-1 Machines Stage-2 Machines
6  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1    17.7000                   8.3000                   0.0000
2    10.0000                   3.5000                   0.0000
6     4.2000                   2.4000                   0.0000
18    1.0000                   1.8000                   0.0000
36   13.6000                   5.6000                   0.0000

                     Stage-1 Machines Stage-2 Machines
1   1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
2   1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
6   1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
18  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
36  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
2    3.7000                   2.9000                   0.0000

  Stage-1 Machines Stage-2 Machines
2         1,2,3,4,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0   15.1000                   7.3000                   0.0000
1   11.9000                   7.8000                   0.0000
4   11.8000                   8.6000                   0.0000

  Stage-1 Machines Stage-2 Machines
0       1,2,3,4,5,              NaN
1       1,2,3,4,5,              NaN
4       1,2,3,4,5,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0   11.1000                   6.4000                   0.0000

  Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
4    11.7000                   8.2000                   0.0000
5    13.5000                   7.8000                   0.0000
8    10.9000                   8.3000                   0.0000
14    1.0000                   0.3000                   0.0000

            Stage-1 Machines Stage-2 Machines
4   1,2,3,4,5,6,7,8,9,10,11,              NaN
5   1,2,3,4,5,6,7,8,9,10,11,              NaN
8   1,2,3,4,5,6,7,8,9,10,11,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
3    5.7000                   0.9000                   0.0000
5   13.7000                   5.7000                   0.0000
6    6.4000                   5.2000                   0.0000

  Stage-1 Machines Stage-2 Machines
3       1,2,3,4,5,              NaN
5       1,2,3,4,5,              NaN
6       1,2,3,4,5,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
13    1.7000                   2.8000                   0.0000

                              Stage-1 Machines Stage-2 Machines
13  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
5    4.1000                   1.2000                   0.0000
8    6.5000                   5.7000                   0.0000

  Stage-1 Machines Stage-2 Machines
5           1,2,3,              NaN
8           1,2,3,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    3.6000                   2.6000                   0.0000
3    2.4000                   0.4000                   0.0000

   Stage-1 Machines Stage-2 Machines
0  1,2,3,4,5,6,7,8,              NaN
3  1,2,3,4,5,6,7,8,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
11    7.0000                   0.1000                   0.0000
16   18.4000                   9.2000                   0.0000
17    1.0000                   0.7000                   0.0000
30    9.0000                   2.8000                   0.0000
32    5.9000                   2.9000                   0.0000
33    6.7000                   4.9000                   0.0000

            Stage-1 Machines Stage-2 Machines
11  1,2,3,4,5,6,7,8,9,10,11,              NaN
16  1,2,3,4,5,6,7,8,9,10,11,              NaN
17  1,2,3,4,5,6,7,8,9,10,11,              NaN
30  1,2,3,4,5,6,7,8,9,10,11,              NaN
32  1,2,3,4,5,6,7,8,9,10,11,              NaN
33  1,2,3,4,5,6,7,8,9,10,11,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    11.5000                   8.2000                   0.0000
1     4.2000                   1.7000                   0.0000
9     1.0000                   0.3000                   0.0000
10    1.7000                   1.3000                   0.0000
11   19.8000                   7.9000                   0.0000

   Stage-1 Machines Stage-2 Machines
0      1,2,3,4,5,6,              NaN
1      1,2,3,4,5,6,              NaN
9      1,2,3,4,5,6,              NaN
10     1,2,3,4,5,6,              NaN
11     1,2,3,4,5,6,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1   12.4000                   5.7000                   0.0000

                                   Stage-1 Machines Stage-2 Machines
1  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0     4.4000                   4.3000                   0.0000
8    10.3000                   9.6000                   0.0000
10    5.1000                   6.5000                   0.0000

    Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,              NaN
8   1,2,3,4,5,6,7,8,              NaN
10  1,2,3,4,5,6,7,8,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    6.7000                   2.2000                   0.0000
1    6.8000                   5.1000                   0.0000

                          Stage-1 Machines Stage-2 Machines
0  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
1  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
40   11.2000                   9.1000                   0.0000

                  Stage-1 Machines Stage-2 Machines
40  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1     1.0000                   2.0000                   0.0000
7     1.0000                   0.4000                   0.0000
8    11.2000                   4.8000                   0.0000
10   17.8000                   7.4000                   0.0000
13    3.2000                   2.8000                   0.0000
24   11.5000                   5.8000                   0.0000
26   13.2000                   9.0000                   0.0000

                                 Stage-1 Machines Stage-2 Machines
1   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
7   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
8   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
10  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
13  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
24  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
26  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
25    1.0000                   2.1000                   0.0000
30   12.1000                   3.9000                   0.0000
34    9.1000                   4.7000                   0.0000

                  Stage-1 Machines Stage-2 Machines
25  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
30  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
34  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6    13.9000                   8.5000                   0.0000
15    4.1000                   2.5000                   0.0000
17   11.5000                   0.3000                   0.0000
21   10.9000                   1.9000                   0.0000
37   11.6000                   6.7000                   0.0000
39    6.2000                   1.2000                   0.0000
41    9.1000                   5.2000                   0.0000

                     Stage-1 Machines Stage-2 Machines
6   1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
15  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
17  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
21  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
37  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
39  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
41  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1   11.0000                   4.6000                   0.0000
2   18.0000                   9.4000                   0.0000
5   11.2000                   3.4000                   0.0000

                             Stage-1 Machines Stage-2 Machines
1  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
2  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
5  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6    17.5000                   1.5000                   0.0000
8     6.1000                   2.3000                   0.0000
14   13.2000                   4.5000                   0.0000
19   20.0000                   8.0000                   0.0000
22   13.2000                   9.3000                   0.0000

    Stage-1 Machines Stage-2 Machines
6   1,2,3,4,5,6,7,8,              NaN
8   1,2,3,4,5,6,7,8,              NaN
14  1,2,3,4,5,6,7,8,              NaN
19  1,2,3,4,5,6,7,8,              NaN
22  1,2,3,4,5,6,7,8,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0     3.7000                   5.8000                   0.0000
10    9.7000                   9.6000                   0.0000
20    6.7000                   2.3000                   0.0000
21    9.7000                   8.0000                   0.0000

               Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,10,11,12,              NaN
10  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
20  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
21  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
3     8.6000                   5.1000                   0.0000
5    23.1000                   9.9000                   0.0000
26   15.1000                   7.6000                   0.0000
35   10.4000                   5.5000                   0.0000
37    1.0000                   1.5000                   0.0000
41    1.5000                   1.4000                   0.0000
43    5.5000                   1.9000                   0.0000
46    9.7000                   5.4000                   0.0000

                                 Stage-1 Machines Stage-2 Machines
3   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
26  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
35  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
37  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
41  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
43  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
46  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
4    20.2000                   9.2000                   0.0000
9     1.0000                   1.1000                   0.0000
14   17.1000                   3.8000                   0.0000
19   10.6000                   3.1000                   0.0000

                        Stage-1 Machines Stage-2 Machines
4   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
9   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
19  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0   12.5000                   7.2000                   0.0000

                       Stage-1 Machines Stage-2 Machines
0  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
5    13.4000                   8.5000                   0.0000
18   10.3000                   2.1000                   0.0000

                        Stage-1 Machines Stage-2 Machines
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
18  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1   12.4000                   4.4000                   0.0000

                    Stage-1 Machines Stage-2 Machines
1  1,2,3,4,5,6,7,8,9,10,11,12,13,14,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
5    14.2000                   9.3000                   0.0000
14    1.0000                   2.2000                   0.0000
17   11.8000                   9.5000                   0.0000
19    1.0000                   1.7000                   0.0000
24   13.6000                   7.4000                   0.0000
31    7.9000                   7.9000                   0.0000

                           Stage-1 Machines Stage-2 Machines
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
17  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
19  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
24  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
31  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1    18.0000                   8.3000                   0.0000
2     1.0000                   3.4000                   0.0000
8     3.4000                   6.1000                   0.0000
17   16.3000                   6.6000                   0.0000

   Stage-1 Machines Stage-2 Machines
1      1,2,3,4,5,6,              NaN
2      1,2,3,4,5,6,              NaN
8      1,2,3,4,5,6,              NaN
17     1,2,3,4,5,6,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
10   17.9000                   5.7000                   0.0000
12    9.9000                   4.0000                   0.0000
13   12.7000                   7.7000                   0.0000
24   10.3000                   4.8000                   0.0000
29    9.4000                   9.4000                   0.0000
30   11.5000                   5.8000                   0.0000
32   12.3000                   9.6000                   0.0000
49    1.2000                   7.1000                   0.0000

                           Stage-1 Machines Stage-2 Machines
10  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
12  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
13  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
24  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN

    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6     4.8000                   2.6000                   0.0000
8     1.0000                   0.7000                   0.0000
25    4.5000                   3.4000                   0.0000
33    5.3000                   1.6000                   0.0000

               Stage-1 Machines Stage-2 Machines
6   1,2,3,4,5,6,7,8,9,10,11,12,              NaN
8   1,2,3,4,5,6,7,8,9,10,11,12,              NaN
25  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
33  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1     4.2000                   8.5000                   0.0000
4    14.8000                   8.6000                   0.0000
9     2.5000                   0.1000                   0.0000
11    1.5000                   3.3000                   0.0000
13   11.3000                   7.9000                   0.0000
14   11.2000                   9.5000                   0.0000

                  Stage-1 Machines Stage-2 Machines
1   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
4   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
9   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
11  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
13  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
2    5.8000                   5.0000                   0.0000
4   10.4000                   5.2000                   0.0000
6    2.4000                   0.8000                   0.0000

                          Stage-1 Machines Stage-2 Machines
2  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
4  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
6  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    12.9000                   8.7000                   0.0000
5     4.0000                   1.3000                   0.0000
18   15.5000                   9.6000                   0.0000
21   24.0000                   7.9000                   0.0000

                                 Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
18  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
21  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
12    4.8000                   4.5000                   0.0000

   Stage-1 Machines Stage-2 Machines
12     1,2,3,4,5,6,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
15    6.2000                   1.1000                   0.0000

               Stage-1 Machines Stage-2 Machines
15  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1    1.0000                   0.1000                   0.0000
2    3.5000                   2.8000                   0.0000
9   15.0000                   3.1000                   0.0000

        Stage-1 Machines Stage-2 Machines
1  1,2,3,4,5,6,7,8,9,10,              NaN
2  1,2,3,4,5,6,7,8,9,10,              NaN
9  1,2,3,4,5,6,7,8,9,10,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
4    8.2000                   5.5000                   0.0000

        Stage-1 Machines Stage-2 Machines
4  1,2,3,4,5,6,7,8,9,10,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
2    9.2000                   6.0000                   0.0000
3    6.4000                   5.0000                   0.0000

  Stage-1 Machines Stage-2 Machines
2         1,2,3,4,              NaN
3         1,2,3,4,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
4   11.2000                   8.1000                   0.0000
7    8.6000                   3.4000                   0.0000

                                   Stage-1 Machines Stage-2 Machines
4  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,              NaN
7  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
5     6.8000                   8.4000                   0.0000
10   11.7000                   6.1000                   0.0000
14   12.5000                   5.1000                   0.0000
17    1.0000                   1.5000                   0.0000
20    7.1000                   0.9000                   0.0000
28   20.3000                   9.7000                   0.0000
37    1.0000                   4.2000                   0.0000
50    8.3000                   8.1000                   0.0000

                        Stage-1 Machines Stage-2 Machines
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
10  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
17  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
20  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
28  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
37  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
50  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
5    15.0000                   7.4000                   0.0000
11    5.2000                   4.5000                   0.0000
12   18.0000                   8.8000                   0.0000
15   11.4000                   7.8000                   0.0000

      Stage-1 Machines Stage-2 Machines
5   1,2,3,4,5,6,7,8,9,              NaN
11  1,2,3,4,5,6,7,8,9,              NaN
12  1,2,3,4,5,6,7,8,9,              NaN
15  1,2,3,4,5,6,7,8,9,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
12   17.1000                   7.7000                   0.0000
17    8.5000                   7.1000                   0.0000
19    7.7000                   5.8000                   0.0000
22    1.0000                   1.0000                   0.0000
23    3.2000                   6.9000                   0.0000
31    1.7000                   4.5000                   0.0000
36    6.0000                   1.5000                   0.0000
43    4.3000                   4.6000                   0.0000
49   14.6000                   7.6000                   0.0000

                           Stage-1 Machines Stage-2 Machines
12  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
17  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
19  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
22  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
23  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
31  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
36  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
43  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
49  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6    12.9000                   9.9000                   0.0000
12   11.2000                   2.6000                   0.0000
16    9.9000                   5.0000                   0.0000

                                 Stage-1 Machines Stage-2 Machines
6   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
12  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
16  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
6    12.1000                   3.9000                   0.0000
7     1.0000                   6.5000                   0.0000
11   15.3000                   7.4000                   0.0000
17    6.9000                   4.7000                   0.0000
19   12.5000                   8.0000                   0.0000
20    6.6000                   4.8000                   0.0000
21    9.5000                   5.9000                   0.0000
23    5.2000                   0.9000                   0.0000
26    7.2000                   9.7000                   0.0000
30   11.8000                   4.5000                   0.0000

                  Stage-1 Machines Stage-2 Machines
6   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
7   1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
11  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
17  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
19  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
20  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
21  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
23  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
26  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
30  1,2,3,4,5,6,7,8,9,10,11,12,13,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
4   11.8000                   8.7000                   0.0000
5    4.8000                   2.2000                   0.0000

  Stage-1 Machines Stage-2 Machines
4         1,2,3,4,              NaN
5         1,2,3,4,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    14.1000                   8.2000                   0.0000
8    13.5000                   4.1000                   0.0000
11    8.8000                   3.8000                   0.0000
19   17.9000                   8.7000                   0.0000
26    5.0000                   0.3000                   0.0000
32    8.5000                   1.9000                   0.0000
34    9.4000                   4.3000                   0.0000
36   10.8000                   7.6000                   0.0000
40   18.5000                   8.4000                   0.0000
41   16.3000                   3.6000                   0.0000
50    6.7000                   2.3000                   0.0000
52    7.3000                   3.4000                   0.0000

                              Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
8   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
11  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
19  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
26  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
32  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
34  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
36  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
40  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
41  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
50  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
52  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0     1.0000                   2.9000                   0.0000
3     2.4000                   2.5000                   0.0000
5     6.7000                   5.9000                   0.0000
10    3.9000                   0.4000                   0.0000
12    3.0000                   2.9000                   0.0000
14   10.8000                   5.9000                   0.0000
21   17.3000                   7.7000                   0.0000
28   12.9000                   4.6000                   0.0000
38    1.0000                   0.7000                   0.0000
41   15.1000                   5.2000                   0.0000
46    1.0000                   6.7000                   0.0000
50   15.0000                   5.9000                   0.0000
52    9.8000                   5.3000                   0.0000

                           Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
3   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
5   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
10  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
12  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
21  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
28  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
38  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
41  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
46  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
50  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
52  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0     6.9000                   3.2000                   0.0000
10   11.7000                   3.1000                   0.0000
13    5.9000                   5.7000                   0.0000
14    4.1000                   6.1000                   0.0000

      Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,              NaN
10  1,2,3,4,5,6,7,8,9,              NaN
13  1,2,3,4,5,6,7,8,9,              NaN
14  1,2,3,4,5,6,7,8,9,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0     3.1000                   0.4000                   0.0000
7    15.3000                   3.9000                   0.0000
14    5.9000                   3.3000                   0.0000
18    1.0000                   1.8000                   0.0000
19    1.0000                   1.2000                   0.0000

      Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,              NaN
7   1,2,3,4,5,6,7,8,9,              NaN
14  1,2,3,4,5,6,7,8,9,              NaN
18  1,2,3,4,5,6,7,8,9,              NaN
19  1,2,3,4,5,6,7,8,9,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    10.1000                   2.9000                   0.0000
8    14.3000                   1.9000                   0.0000
13    6.1000                   3.1000                   0.0000
16    1.0000                   4.8000                   0.0000
22    1.6000                   3.0000                   0.0000
23    8.1000                   5.4000                   0.0000
24    3.5000                   1.5000                   0.0000
25    8.6000                   4.1000                   0.0000
29    1.0000                   2.1000                   0.0000
32    6.1000                   1.2000                   0.0000
33   20.9000                   5.8000                   0.0000
47    1.0000                   0.3000                   0.0000
48   13.3000                   6.3000                   0.0000

                           Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
8   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
13  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
16  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
22  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
23  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
24  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
25  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
29  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
32  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
33  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
47  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
48  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0   24.0000                   9.3000                   0.0000

           Stage-1 Machines Stage-2 Machines
0  1,2,3,4,5,6,7,8,9,10,11,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
4    15.6000                   8.2000                   0.0000
6     7.8000                   1.8000                   0.0000
14    9.7000                   3.6000                   0.0000
15    5.3000                   2.2000                   0.0000
21    9.2000                   5.0000                   0.0000

                        Stage-1 Machines Stage-2 Machines
4   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
6   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
14  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
15  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
21  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    13.4000                   6.5000                   0.0000
2    11.3000                   3.7000                   0.0000
3     7.0000                   0.9000                   0.0000
9     1.0000                   0.5000                   0.0000
12    8.9000                   6.7000                   0.0000
13    3.4000                   2.4000                   0.0000
15   24.0000                   8.7000                   0.0000

                              Stage-1 Machines Stage-2 Machines
0   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
2   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
3   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
9   1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
12  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
13  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
15  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,              NaN
Empty DataFrame
Columns: [Due Time, Stage-1 Processing Time, Stage-2 Processing Time, Stage-1 Machines, Stage-2 Machines]
Index: []
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
1   10.0000                   2.6000                   0.0000
2    7.7000                   5.6000                   0.0000

  Stage-1 Machines Stage-2 Machines
1       1,2,3,4,5,              NaN
2       1,2,3,4,5,              NaN
   Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0   16.8000                   5.7000                   0.0000
2   13.4000                   7.9000                   0.0000
3    6.2000                   1.3000                   0.0000
8   17.5000                   8.2000                   0.0000

              Stage-1 Machines Stage-2 Machines
0  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
2  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
3  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
8  1,2,3,4,5,6,7,8,9,10,11,12,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
8    10.8000                   1.1000                   0.0000
17    4.9000                   6.3000                   0.0000

    Stage-1 Machines Stage-2 Machines
8   1,2,3,4,5,6,7,8,              NaN
17  1,2,3,4,5,6,7,8,              NaN
    Due Time  Stage-1 Processing Time  Stage-2 Processing Time  \
0    15.9000                   4.7000                   0.0000
2    14.0000                   8.3000                   0.0000
8    10.0000                   2.2000                   0.0000
9    14.2000                   5.5000                   0.0000
10    1.0000                   0.8000                   0.0000
26   13.5000                   5.3000                   0.0000