In [49]:
from gurobipy import *
import pandas as pd
import numpy as np
import os

# display settings
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.set_option('display.float_format', lambda x: '%.4f' % x)

## data input

In [112]:
print(os.getcwd())
os.chdir("../to students/data")
print(os.getcwd())
os.listdir()

/Users/wangyanpu/Desktop/台灣大學/大三下/作業研究/case/Case2/to students/data

FileNotFoundError: [Errno 2] No such file or directory: '../to students/data'

In [79]:
df = pd.read_csv("instance 1.csv", index_col=0)
display(df)

,Stage-1 Processing Time,Stage-2 Processing Time,Stage-1 Machines,Stage-2 Machines,Due Time
Job ID,,,,,
1,2.7000,1.3000,"1,2,3,4,5","2,3,4,5",5
2,1.6000,1.4000,"2,3,4,5","1,2,3,4,5",5
3,0.7000,1.9000,"1,2,3,4,5","2,3,4,5",5
4,0.5000,0.7000,"2,3,4,5","1,2,3,4,5",5
5,0.8000,1.0000,"1,2,3,4,5","2,3,4,5",5
6,2.5000,0.0000,"1,2,3,4,5",NaN,5
7,1.4000,2.0000,"2,3,4,5","2,3,4,5",5
8,1.1000,1.1000,"2,3,4,5","2,3,4,5",10
9,0.8000,0.7000,"1,2,3,4,5","2,3,4,5",10
10,1.0000,0.5000,"2,3,4,5","1,2,3,4,5",10
11,3.0000,1.4000,"1,2,3,4,5","2,3,4,5",10
12,2.0000,0.0000,"2,3,4,5",NaN,10

In [80]:
mfor1 = df['Stage-1 Machines'].values
mfor2 = df['Stage-2 Machines'].values
mfor1 = [list(map(int, x.split(','))) for x in mfor1]
mfor2 = [list(map(int, x.split(','))) for x in mfor2 if x is not np.nan]
mfor1 = [item for sublist in mfor1 for item in sublist]
mfor2 = [item for sublist in mfor2 for item in sublist]
machine_set = list(set(mfor1 + mfor2))
print(machine_set)

[1, 2, 3, 4, 5]

In [81]:
def split_(row):
    if row is np.nan:
        return list(machine_set)
    else:
        return list(map(int, row.split(",")))

In [82]:
df["Stage-1 Machines"] = df["Stage-1 Machines"].apply(split_)
df["Stage-2 Machines"] = df["Stage-2 Machines"].apply(split_)

df.iloc[0, 2]

[1, 2, 3, 4, 5]

In [83]:
from sklearn.preprocessing import MultiLabelBinarizer
stage1 = df["Stage-1 Machines"]
stage2 = df["Stage-2 Machines"]

mlb = MultiLabelBinarizer()
mlb2 = MultiLabelBinarizer()
dummyM1_df = pd.DataFrame(mlb.fit_transform(stage1), columns=mlb.classes_, index=df.index)
dummyM1_df = dummyM1_df.add_prefix("stage1_m")
dummyM2_df = pd.DataFrame(mlb2.fit_transform(stage2), columns=mlb2.classes_, index=df.index)
dummyM2_df = dummyM2_df.add_prefix("stage2_m")
dummyM1_df, dummyM2_df

(        stage1_m1  stage1_m2  stage1_m3  stage1_m4  stage1_m5
 Job ID
 1               1          1          1          1          1
 2               0          1          1          1          1
 3               1          1          1          1          1
 4               0          1          1          1          1
 5               1          1          1          1          1
 6               1          1          1          1          1
 7               0          1          1          1          1
 8               0          1          1          1          1
 9               1          1          1          1          1
 10              0          1          1          1          1
 11              1          1          1          1          1
 12              0          1          1          1          1,
         stage2_m1  stage2_m2  stage2_m3  stage2_m4  stage2_m5
 Job ID
 1               0          1          1          1          1
 2               1          1          1          1          1
 3               0          1          1          1          1
 4               1          1          1          1          1
 5               0          1          1          1          1
 6               1          1          1          1          1
 7               0          1          1          1          1
 8               0          1          1          1          1
 9               0          1          1          1          1
 10              1          1          1          1          1
 11              0          1          1          1          1
 12              1          1          1          1          1)

In [84]:
dummyM1_col = dummyM1_df.columns
dummyM2_col = dummyM2_df.columns
print(dummyM1_col, dummyM2_col)

df = df.join(dummyM1_df, on="Job ID")
df = df.join(dummyM2_df, on="Job ID")
df = df.drop(["Stage-1 Machines", "Stage-2 Machines"], axis=1)
df

Index(['stage1_m1', 'stage1_m2', 'stage1_m3', 'stage1_m4', 'stage1_m5'], dtype='object') Index(['stage2_m1', 'stage2_m2', 'stage2_m3', 'stage2_m4', 'stage2_m5'], dtype='object')

,Stage-1 Processing Time,Stage-2 Processing Time,Due Time,stage1_m1,stage1_m2,stage1_m3,stage1_m4,stage1_m5,stage2_m1,stage2_m2,stage2_m3,stage2_m4,stage2_m5
Job ID,,,,,,,,,,,,,
1,2.7000,1.3000,5,1,1,1,1,1,0,1,1,1,1
2,1.6000,1.4000,5,0,1,1,1,1,1,1,1,1,1
3,0.7000,1.9000,5,1,1,1,1,1,0,1,1,1,1
4,0.5000,0.7000,5,0,1,1,1,1,1,1,1,1,1
5,0.8000,1.0000,5,1,1,1,1,1,0,1,1,1,1
6,2.5000,0.0000,5,1,1,1,1,1,1,1,1,1,1
7,1.4000,2.0000,5,0,1,1,1,1,0,1,1,1,1
8,1.1000,1.1000,10,0,1,1,1,1,0,1,1,1,1
9,0.8000,0.7000,10,1,1,1,1,1,0,1,1,1,1
10,1.0000,0.5000,10,0,1,1,1,1,1,1,1,1,1
11,3.0000,1.4000,10,1,1,1,1,1,0,1,1,1,1
12,2.0000,0.0000,10,0,1,1,1,1,1,1,1,1,1

In [100]:
instance = df
display(instance)
print(instance.index)

pt_stage1 = instance["Stage-1 Processing Time"].values
pt_stage2 = instance["Stage-2 Processing Time"].values
due_time = instance["Due Time"].values

job_id = list(instance.index)
print(job_id)
m_dummy_stage1 = instance[dummyM1_col].values
m_dummy_stage2 = instance[dummyM2_col].values
print(m_dummy_stage1)
print(m_dummy_stage2)

print(machine_set)
L = (sum(pt_stage1) + sum(pt_stage2)) * 100
print(L)

print(due_time)
print(pt_stage1)

,Stage-1 Processing Time,Stage-2 Processing Time,Due Time,stage1_m1,stage1_m2,stage1_m3,stage1_m4,stage1_m5,stage2_m1,stage2_m2,stage2_m3,stage2_m4,stage2_m5
Job ID,,,,,,,,,,,,,
1,2.7000,1.3000,5,1,1,1,1,1,0,1,1,1,1
2,1.6000,1.4000,5,0,1,1,1,1,1,1,1,1,1
3,0.7000,1.9000,5,1,1,1,1,1,0,1,1,1,1
4,0.5000,0.7000,5,0,1,1,1,1,1,1,1,1,1
5,0.8000,1.0000,5,1,1,1,1,1,0,1,1,1,1
6,2.5000,0.0000,5,1,1,1,1,1,1,1,1,1,1
7,1.4000,2.0000,5,0,1,1,1,1,0,1,1,1,1
8,1.1000,1.1000,10,0,1,1,1,1,0,1,1,1,1
9,0.8000,0.7000,10,1,1,1,1,1,0,1,1,1,1
10,1.0000,0.5000,10,0,1,1,1,1,1,1,1,1,1
11,3.0000,1.4000,10,1,1,1,1,1,0,1,1,1,1
12,2.0000,0.0000,10,0,1,1,1,1,1,1,1,1,1

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype='int64', name='Job ID')
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[[1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]]
[[0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]]
[1, 2, 3, 4, 5]
3010.0
[ 5  5  5  5  5  5  5 10 10 10 10 10]
[2.7 1.6 0.7 0.5 0.8 2.5 1.4 1.1 0.8 1.  3.  2. ]

## Modeling

### part1

In [101]:
p1 = Model("p1")
j_num = int(len(job_id))
m_len = len(machine_set)

# Variables
s_jkm = []
c_jkm = []
x_jkm = []
for j in range(j_num):
    tmp_s = []
    tmp_c = []
    tmp_x = []
    for k in range(2):
        tmp_s.append([])
        tmp_c.append([])
        tmp_x.append([])
        for m in machine_set:
            tmp_s[k].append(p1.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "s_" + str(j + 1) + "," + str(k + 1) + "," + str(m)))
            tmp_c[k].append(p1.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "c_" + str(j + 1) + "," + str(k + 1) + "," + str(m)))
            tmp_x[k].append(p1.addVar(lb = 0, vtype = GRB.BINARY, name = "x_" + str(j + 1) + "," + str(k) + ","+ str(m)))  
    s_jkm.append(tmp_s)
    c_jkm.append(tmp_c)
    x_jkm.append(tmp_x)
print(len(x_jkm))
print(len(x_jkm[0]))
print(len(x_jkm[0][0]))

y_jkjkm = []
for j1 in range(j_num):
    y_jkjkm.append([])
    for k1 in range(2):
        y_jkjkm[j1].append([])
        for j2 in range(j1 + 1, j_num):
            y_jkjkm[j1][k1].append([])
            for k2 in range(2):
                y_jkjkm[j1][k1][j2 - j1 - 1].append([])
                for m in machine_set:
#                     print(j1 + 1, k1 + 1, j2 + 1, k2 + 1, m)
                    y_jkjkm[j1][k1][j2 - j1 - 1][k2].append(p1.addVar(lb = 0, vtype = GRB.BINARY, 
                                                   name = "y_" + str(j1 + 1) + "," + str(k1 + 1) + "," + str(j2 + 1) + "," + str(k2 + 1)+ "," + str(m)))

c_j = []
for j in range(j_num):
    c_j.append(p1.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "c_" + str(j + 1)))
t_j = []
for j in range(j_num):
    t_j.append(p1.addVar(lb = 0, vtype = GRB.BINARY, name = "t_" + str(j + 1)))

12
2
5

In [102]:
# setting the objective function 
p1.setObjective(quicksum(t_j[j] for j in range(j_num)), GRB.MINIMIZE)

In [103]:
# add constraints and name them

# stage 1 machine limit
p1.addConstrs((x_jkm[j][0][m] <= m_dummy_stage1[j][m] for j in range(j_num) for m in range(m_len)))
# stage 2 machine limit
p1.addConstrs((x_jkm[j][1][m] <= m_dummy_stage2[j][m] for j in range(j_num) for m in range(m_len)))

# tardy variable
p1.addConstrs((t_j[j] * L >= c_j[j] - due_time[j] 
                for j in range(j_num)), "tardy count")

# job complete time
p1.addConstrs((c_j[j] >= quicksum(c_jkm[j][1][m] for m in range(m_len))
                for j in range(j_num)), "job completion time")

# each job assigned once
p1.addConstrs((quicksum(x_jkm[j][k][m] for m in range(m_len)) == 1 for j in range(j_num) for k in range(2)), "job assignment constraint")

p1.addConstrs((s_jkm[j][k][m] + c_jkm[j][k][m] <= x_jkm[j][k][m] * L for j in range(j_num) for k in range(2) for m in range(m_len)))

# process time
p1.addConstrs((c_jkm[j][0][m] >= s_jkm[j][0][m] + pt_stage1[j] - (1 - x_jkm[j][0][m]) * L for j in range(j_num) for m in range(m_len)))
p1.addConstrs((c_jkm[j][1][m] >= s_jkm[j][1][m] + pt_stage2[j] - (1 - x_jkm[j][1][m]) * L for j in range(j_num) for m in range(m_len)))

for m in range(m_len):
    for j1 in range(j_num):
        for k1 in range(2):
            for j2 in range(j_num - j1 - 1):
                for k2 in range(2):
                # 注意ijm的indexing方法不同
                    p1.addConstr(s_jkm[j1][k1][m] >= c_jkm[j1 + j2 + 1][k2][m] - y_jkjkm[j1][k1][j2][k2][m] * L)
                    p1.addConstr(s_jkm[j1 + j2 + 1][k2][m] >= c_jkm[j1][k1][m] - (1 - y_jkjkm[j1][k1][j2][k2][m]) * L)
            
# subjob 2 starts only after subjob 1
p1.addConstrs((quicksum(s_jkm[j][1][m] for m in range(m_len)) >= quicksum(c_jkm[j][0][m] for m in range(m_len)) for j in range(j_num)), "subjob 1 ends before subjob2 starts")

{0: <gurobi.Constr *Awaiting Model Update*>,
 1: <gurobi.Constr *Awaiting Model Update*>,
 2: <gurobi.Constr *Awaiting Model Update*>,
 3: <gurobi.Constr *Awaiting Model Update*>,
 4: <gurobi.Constr *Awaiting Model Update*>,
 5: <gurobi.Constr *Awaiting Model Update*>,
 6: <gurobi.Constr *Awaiting Model Update*>,
 7: <gurobi.Constr *Awaiting Model Update*>,
 8: <gurobi.Constr *Awaiting Model Update*>,
 9: <gurobi.Constr *Awaiting Model Update*>,
 10: <gurobi.Constr *Awaiting Model Update*>,
 11: <gurobi.Constr *Awaiting Model Update*>}

In [104]:
p1.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (mac64[arm])
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads
Optimize a model with 3060 rows, 1704 columns and 9096 nonzeros
Model fingerprint: 0xa8ae6784
Variable types: 252 continuous, 1452 integer (1452 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+03]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 3e+03]
Presolve removed 603 rows and 286 columns
Presolve time: 0.02s
Presolved: 2457 rows, 1418 columns, 7453 nonzeros
Variable types: 204 continuous, 1214 integer (1214 binary)
Found heuristic solution: objective 8.0000000

Root relaxation: objective 0.000000e+00, 325 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.00000    0    8    8.00000    0.00000   100%     -    0s
H    0     0                       3.0000000    0.00000   100%     -    0s
     0     0    0.00000    0   12    3.00000    0.00000   100%     -    0s
H    0     0                       0.0000000    0.00000  0.00%     -    0s
     0     0    0.00000    0   12    0.00000    0.00000  0.00%     -    0s

Cutting planes:
  MIR: 1
  Flow cover: 2
  RLT: 1

Explored 1 nodes (1421 simplex iterations) in 0.08 seconds (0.08 work units)
Thread count was 10 (of 10 available processors)

Solution count 3: 0 3 8

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%

In [105]:
p1.objVal

0.0

### part2

In [108]:
p1_2 = Model("p1_2")
p1_2.setParam('TimeLimit', 5*60)
j_num = int(len(job_id))
m_len = len(machine_set)

# tardy job num result from part 1
T = p1.objVal

# Variables
u = p1_2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "u")
s_jkm = []
c_jkm = []
x_jkm = []
for j in range(j_num):
    tmp_s = []
    tmp_c = []
    tmp_x = []
    for k in range(2):
        tmp_s.append([])
        tmp_c.append([])
        tmp_x.append([])
        for m in machine_set:
            tmp_s[k].append(p1_2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "s_" + str(j + 1) + "," + str(k + 1) + "," + str(m)))
            tmp_c[k].append(p1_2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "c_" + str(j + 1) + "," + str(k + 1) + "," + str(m)))
            tmp_x[k].append(p1_2.addVar(lb = 0, vtype = GRB.BINARY, name = "x_" + str(j + 1) + "," + str(k) + ","+ str(m)))  
    s_jkm.append(tmp_s)
    c_jkm.append(tmp_c)
    x_jkm.append(tmp_x)
print(len(x_jkm))
print(len(x_jkm[0]))
print(len(x_jkm[0][0]))

y_jkjkm = []
for j1 in range(j_num):
    y_jkjkm.append([])
    for k1 in range(2):
        y_jkjkm[j1].append([])
        for j2 in range(j1 + 1, j_num):
            y_jkjkm[j1][k1].append([])
            for k2 in range(2):
                y_jkjkm[j1][k1][j2 - j1 - 1].append([])
                for m in machine_set:
#                     print(j1 + 1, k1 + 1, j2 + 1, k2 + 1, m)
                    y_jkjkm[j1][k1][j2 - j1 - 1][k2].append(p1_2.addVar(lb = 0, vtype = GRB.BINARY, 
                                                   name = "y_" + str(j1 + 1) + "," + str(k1 + 1) + "," + str(j2 + 1) + "," + str(k2 + 1)+ "," + str(m)))

c_j = []
for j in range(j_num):
    c_j.append(p1_2.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = "c_" + str(j + 1)))
t_j = []
for j in range(j_num):
    t_j.append(p1_2.addVar(lb = 0, vtype = GRB.BINARY, name = "t_" + str(j + 1)))

Set parameter TimeLimit to value 300
12
2
5

In [109]:
# setting the objective function 
p1_2.setObjective(u, GRB.MINIMIZE)

In [110]:
# add constraints and name them

# new constraints
p1_2.addConstrs((u >= c_j[j] for j in range(j_num)))
p1_2.addConstr((quicksum(t_j[j] for j in range(j_num)) == T))

# stage 1 machine limit
p1_2.addConstrs((x_jkm[j][0][m] <= m_dummy_stage1[j][m] for j in range(j_num) for m in range(m_len)))
# stage 2 machine limit
p1_2.addConstrs((x_jkm[j][1][m] <= m_dummy_stage2[j][m] for j in range(j_num) for m in range(m_len)))

# tardy variable
p1_2.addConstrs((t_j[j] * L >= c_j[j] - due_time[j] 
                for j in range(j_num)), "tardy count")

# job complete time
p1_2.addConstrs((c_j[j] >= quicksum(c_jkm[j][1][m] for m in range(m_len))
                for j in range(j_num)), "job completion time")

# each job assigned once
p1_2.addConstrs((quicksum(x_jkm[j][k][m] for m in range(m_len)) == 1 for j in range(j_num) for k in range(2)), "job assignment constraint")

p1_2.addConstrs((s_jkm[j][k][m] + c_jkm[j][k][m] <= x_jkm[j][k][m] * L for j in range(j_num) for k in range(2) for m in range(m_len)))

# process time
p1_2.addConstrs((c_jkm[j][0][m] >= s_jkm[j][0][m] + pt_stage1[j] - (1 - x_jkm[j][0][m]) * L for j in range(j_num) for m in range(m_len)))
p1_2.addConstrs((c_jkm[j][1][m] >= s_jkm[j][1][m] + pt_stage2[j] - (1 - x_jkm[j][1][m]) * L for j in range(j_num) for m in range(m_len)))

for m in range(m_len):
    for j1 in range(j_num):
        for k1 in range(2):
            for j2 in range(j_num - j1 - 1):
                for k2 in range(2):
                # 注意ijm的indexing方法不同
    #             print(i, j, m)
    #             print(i, i + j + 1, m)
    #             print()
                    p1_2.addConstr(s_jkm[j1][k1][m] >= c_jkm[j1 + j2 + 1][k2][m] - y_jkjkm[j1][k1][j2][k2][m] * L)
                    p1_2.addConstr(s_jkm[j1 + j2 + 1][k2][m] >= c_jkm[j1][k1][m] - (1 - y_jkjkm[j1][k1][j2][k2][m]) * L)
            
# subjob 2 starts only after subjob 1
p1_2.addConstrs((quicksum(s_jkm[j][1][m] for m in range(m_len)) >= quicksum(c_jkm[j][0][m] for m in range(m_len)) for j in range(j_num)), "subjob 1 ends before subjob2 starts")

{0: <gurobi.Constr *Awaiting Model Update*>,
 1: <gurobi.Constr *Awaiting Model Update*>,
 2: <gurobi.Constr *Awaiting Model Update*>,
 3: <gurobi.Constr *Awaiting Model Update*>,
 4: <gurobi.Constr *Awaiting Model Update*>,
 5: <gurobi.Constr *Awaiting Model Update*>,
 6: <gurobi.Constr *Awaiting Model Update*>,
 7: <gurobi.Constr *Awaiting Model Update*>,
 8: <gurobi.Constr *Awaiting Model Update*>,
 9: <gurobi.Constr *Awaiting Model Update*>,
 10: <gurobi.Constr *Awaiting Model Update*>,
 11: <gurobi.Constr *Awaiting Model Update*>}

In [111]:
p1_2.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (mac64[arm])
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads
Optimize a model with 3073 rows, 1705 columns and 9132 nonzeros
Model fingerprint: 0x63abdb98
Variable types: 253 continuous, 1452 integer (1452 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+03]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 3e+03]
Presolve removed 604 rows and 286 columns
Presolve time: 0.02s
Presolved: 2469 rows, 1419 columns, 7504 nonzeros
Variable types: 217 continuous, 1202 integer (1202 binary)

Root relaxation: objective 4.400000e+00, 617 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    4.40000    0   16          -    4.40000      -     -    0s
     0     0    4.40000    0   21          -    4.40000      -     -    0s
     0     0    4.40000    0   12          -    4.40000      -     -    0s
H    0     0                      10.0000000    4.40000  56.0%     -    0s
H    0     0                       9.8000000    4.40000  55.1%     -    0s
H    0     0                       8.9000000    4.40000  50.6%     -    0s
     0     0    4.40000    0   22    8.90000    4.40000  50.6%     -    0s
H    0     0                       8.4000000    4.40000  47.6%     -    0s
H    0     0                       7.9000000    4.40000  44.3%     -    0s
     0     0    4.40000    0   24    7.90000    4.40000  44.3%     -    0s
     0     0    4.40000    0   18    7.90000    4.40000  44.3%     -    0s
     0     0    4.40000    0   19    7.90000    4.40000  44.3%     -    0s
H    0     0                       7.8000000    4.40000  43.6%     -    0s
H    0     0                       7.4000000    4.40000  40.5%     -    0s
     0     0    4.40000    0   18    7.40000    4.40000  40.5%     -    0s
     0     0    4.40000    0   17    7.40000    4.40000  40.5%     -    0s
     0     0    4.40000    0   21    7.40000    4.40000  40.5%     -    0s
     0     0    4.40000    0   21    7.40000    4.40000  40.5%     -    0s
     0     2    4.40000    0   19    7.40000    4.40000  40.5%     -    0s
H  482   481                       6.9000000    4.40000  36.2%  11.4    0s
H  767   660                       6.8000000    4.40000  35.3%  11.4    0s
H 1339   857                       6.4000000    4.40000  31.2%  11.5    0s
* 2397  1380              41       6.2000000    4.40000  29.0%  18.1    1s
H 3006  1715                       6.1000000    4.40000  27.9%  19.1    1s
 17389  8794    4.40000   39   47    6.10000    4.40000  27.9%  28.9    5s
 32928 14509    5.00000   44   16    6.10000    4.40000  27.9%  33.4   10s
H47135 19030                       6.1000000    4.40000  27.9%  34.6   13s
 52606 21870    4.40000   43   26    6.10000    4.40000  27.9%  34.8   15s
 76102 29626    5.40000   49   23    6.10000    4.40000  27.9%  35.4   20s
 100548 37575 infeasible   52         6.10000    4.40000  27.9%  36.1   25s
 122914 45054    4.40000   35   32    6.10000    4.40000  27.9%  36.3   30s
H130393 47267                       6.1000000    4.40000  27.9%  36.4   31s
 145509 52025    4.40000   34   24    6.10000    4.40000  27.9%  36.4   35s
 165481 58430    4.70000   46   50    6.10000    4.40000  27.9%  36.4   40s
 184304 64595    4.40000   38   51    6.10000    4.40000  27.9%  36.2   45s
 208448 71629    4.40000   44   42    6.10000    4.40000  27.9%  36.1   50s
H214373 73000                       6.0999993    4.40000  27.9%  36.0   51s
 229785 77663    4.40000   42   32    6.10000    4.40000  27.9%  36.0   55s
 250882 82710    5.00000   51   21    6.10000    4.40000  27.9%  36.1   60s
 274160 89005 infeasible   48         6.10000    4.40000  27.9%  36.3   65s
 295395 94731    5.10000   49   23    6.10000    4.40000  27.9%  36.4   70s
 317053 100296     cutoff   65         6.10000    4.40000  27.9%  36.4   75s
 337052 106169 infeasible   63         6.10000    4.40000  27.9%  36.3   80s
 357937 111482    6.00000   57   10    6.10000    4.40000  27.9%  36.4   85s
 381974 116723    4.40000   42   46    6.10000    4.40000  27.9%  36.6   90s
 401468 121206 infeasible   52         6.10000    4.40000  27.9%  36.8   95s
 418809 125052    4.60000   61   56    6.10000    4.40000  27.9%  37.0  100s
 437792 128638    5.90000   56   18    6.10000    4.40000  27.9%  37.3  105s
 459737 132916 infeasible   57         6.10000    4.40000  27.9%  37.5  110s
 478796 136853    6.00000   53   23    6.10000    4.40000  27.9%  37.7  115s
 498298 141521    4.70000   62   23    6.10000    4.40000  27.9%  37.7  120s
 520840 146728     cutoff   47         6.10000    4.40000  27.9%  37.7  125s
 539998 151211 infeasible   62         6.10000    4.40000  27.9%  37.8  130s
 560433 155883    6.00000   29   25    6.10000    4.40000  27.9%  37.9  135s
 584003 161561    5.90000   44    8    6.10000    4.40000  27.9%  37.9  140s
 604314 167365    6.00000   55   15    6.10000    4.40000  27.9%  37.8  145s
 625475 172971    5.10000   46   34    6.10000    4.40000  27.9%  37.8  150s
 645937 178713    6.00000   55   26    6.10000    4.40000  27.9%  37.8  155s
 669331 185671 infeasible   39         6.10000    4.40000  27.9%  37.7  160s
 690127 191604    4.90000   41   44    6.10000    4.40000  27.9%  37.6  165s
 712236 197723 infeasible   46         6.10000    4.40000  27.9%  37.6  170s
 734753 203599    5.60000   42   20    6.10000    4.40000  27.9%  37.5  175s
 756444 209469 infeasible   49         6.10000    4.40000  27.9%  37.5  180s
 776987 214632    5.90000   50   19    6.10000    4.40000  27.9%  37.5  185s
 799065 219690    5.00000   60   30    6.10000    4.40000  27.9%  37.6  190s
 819636 223437 infeasible   64         6.10000    4.40000  27.9%  37.6  195s
 841643 228802    5.40000   50   21    6.10000    4.40000  27.9%  37.7  200s
 864775 233845     cutoff   63         6.10000    4.40000  27.9%  37.7  205s
 886392 239530    6.00000   67   30    6.10000    4.40000  27.9%  37.7  210s
 906829 244604    4.40000   39   28    6.10000    4.40000  27.9%  37.7  215s
 928510 249590 infeasible   53         6.10000    4.40000  27.9%  37.8  220s
 948722 254370    5.50000   55   34    6.10000    4.40000  27.9%  37.8  225s
 972276 260153    6.00000   64   24    6.10000    4.40000  27.9%  37.8  230s
 994767 265998 infeasible   45         6.10000    4.40000  27.9%  37.8  235s
 1017496 271982    4.60000   44   41    6.10000    4.40000  27.9%  37.8  240s
 1039076 277586    5.20000   59   16    6.10000    4.40000  27.9%  37.8  245s
 1057723 282467    4.60000   52   49    6.10000    4.40000  27.9%  37.8  250s
 1078575 287584    5.40000   38   41    6.10000    4.40000  27.9%  37.8  255s
 1102233 292880 infeasible   56         6.10000    4.40000  27.9%  37.8  260s
 1122823 298348    5.70000   57   15    6.10000    4.40000  27.9%  37.8  265s
 1145797 303747 infeasible   42         6.10000    4.40000  27.9%  37.8  270s
 1165802 308629    5.50000   43   38    6.10000    4.40000  27.9%  37.9  275s
 1188792 313829    5.60000   46   15    6.10000    4.40000  27.9%  37.9  280s
 1213115 319482    5.60000   55   15    6.10000    4.40000  27.9%  37.9  285s
 1236805 326216 infeasible   63         6.10000    4.40000  27.9%  37.8  290s
 1260794 332022 infeasible   48         6.10000    4.40000  27.9%  37.8  295s
 1283907 337060    5.40000   43   31    6.10000    4.40000  27.9%  37.8  300s

Cutting planes:
  Gomory: 5
  Cover: 12
  Implied bound: 4
  Clique: 3
  MIR: 3
  Flow cover: 23
  RLT: 16
  Relax-and-lift: 1

Explored 1283919 nodes (48591299 simplex iterations) in 300.01 seconds (421.42 work units)
Thread count was 10 (of 10 available processors)

Solution count 10: 6.1 6.1 6.1 ... 7.4

Time limit reached
Best objective 6.099999305578e+00, best bound 4.400000000000e+00, gap 27.8688%

In [113]:
p1_2.objVal

6.09999930557768